defaultHook:
  type: merkleTreeHook
defaultIsm:
  threshold: 1
  type: messageIdMultisigIsm
  validators:
    - "0x0429A2Da7884CA14E53142988D5845952fE4DF6a"
owner: "0x0429A2Da7884CA14E53142988D5845952fE4DF6a"
requiredHook:
  type: merkleTreeHook

